# Generated by Django 3.2.5 on 2021-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umb_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='alert',
            field=models.CharField(default=1, max_length=191),
            preserve_default=False,
        ),
    ]
