# Generated by Django 3.2.5 on 2021-07-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umb_admin', '0002_weight_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='price_price',
            new_name='amount_price',
        ),
    ]
