# Generated by Django 3.2.5 on 2021-07-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umb_admin', '0003_rename_price_price_weight_amount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('alert', 'Lansiran'), ('discount', 'Potongan'), ('price', 'Price')], max_length=191)),
                ('value', models.CharField(max_length=191)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-id'], 'verbose_name': 'Weight', 'verbose_name_plural': 'Weights'},
        ),
        migrations.AlterField(
            model_name='weight',
            name='paid_off',
            field=models.BooleanField(default=False),
        ),
    ]
